name: Build and Package Extension

# run this action on main branch and every pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

common_steps: &common_steps
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Install Rust
    uses: dtolnay/rust-toolchain@nightly
    with:
      target: wasm32-unknown-unknown

  - uses: actions/cache@v4
    with:
      path: |
        ~/.cargo/bin/
        ~/.cargo/registry/index/
        ~/.cargo/registry/cache/
        ~/.cargo/git/db/
        target/
      key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

  - name: Install cargo-binstall
    run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

  - name: Install wasm-pack
    run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

  - name: Install trunk and just
    run: cargo binstall trunk just

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code

        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown,x86_64-unknown-linux-gnu

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install trunk and just
        run: cargo binstall trunk just

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo clippy
        run: just clippy

      - name: Cargo build
        run: just build

      - name: Cargo build extension
        run: just be

      - name: Upload firefox extension
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension
          path: crates/nexum/extension/dist/
